### ISSUE TITLE
Test: CalendarController Test 작성 및 리팩토링

### ISSUE THREAD

**Issue by YongsHub** [wooda-ege/lovebird-server#56]
## Description

> CalendarController Test Code 작성과 CodeSnippet을 리팩토링합니다

## To-do

- [x] CalendarController Test Code 작성
- [x] Rest Docs 작성
- [x] Custom ResponseSnippet 추가
