### ISSUE TITLE
Test: Diary Unit Test With Controller Test

### ISSUE THREAD

**Issue by YongsHub** [wooda-ege/lovebird-server#60]
## Description

> Diary Domain Test Code

## To-do

- [x] Diary Unit Test
- [x] Decrypt와 Encrypt 책임 분리
- [x] Service 간 순환 참조 방지
- [x] Decrypt 중복 제거
- [x] 예외 테스트를 위해 Entity Exception -> Custom Exception 으로 변경
- [x] fixture 생성 클래스 추가
